### PR TITLE
Added Arrow up and down events to Track and Octave controls

### PR DESCRIPTION
**Pull request by dmportella**
Simple addition of the key events

Had to use keyup event since that keydown does not emitt arrow keys its  known bug in xaml

### CODE REVIEW

**Comment by dmportella** [comment]
let me know if you need anything extra

**Comment by troy-f** [comment]
@dmportella please pull latest develop branch into your fork

**Comment by Meowchestra** [comment]
@dmportella Why do you need to be able to change octave / track boxes with numpad? I'd assume the bmp client would need to be focused so if you use numpad keys in-game it doesn't affect bmp, and you'd have to focus on the box by clicking anyways because if you have multiple performers attached, how does it decide which box to affect?

**Comment by dmportella** [comment]
> @dmportella Why do you need to be able to change octave / track boxes with numpad? I'd assume the bmp client would need to be focused so if you use numpad keys in-game it doesn't affect bmp, and you'd have to focus on the box by clicking anyways because if you have multiple performers attached, how does it decide which box to affect?

its not for the numpad its for the arrow keys (up down left right)
Just standard functionality of a number box 

* pressing up number goes up 
* pressing down number goes down.

Not using bots or multiple clients, this is just the tabbing the controls and being able to change values using only the keyboard many bards are not using multiple clients and being able to tab and change values which is quicker then clicking with the mouse a tiny UP and Down Arrow helps.

Hope makes sense

**Comment by Meowchestra** [comment]
Even still, people use arrow keys to pan the camera around in-game. So you would need to window focus into bmp if you wanted to change tracks/octaves as to not affect bmp when you unintentionally use arrows. And similarly, those that _do_ use multiple clients for ensemble play, you would need to focus on the box anyways by clicking to specify which track / octave you want to shift specifically as to not affect all performers. If you are clicking into the box already, arrow keys seem a bit redundant to me.

If it works _only_ when a box is focused to more quickly shift tracks and that box specifically, then I suppose it may be fine. There are just those things to consider if not.

_I haven't actually tested this PR, just theorizing problems._

**Comment by dmportella** [comment]
> 

Exactly! You need to have to focused just like a normal windows controls with behaviour that people would expect. not making this for the examples you given. We use it like this, we have bmp focused and we usually use keyboard to do things.

**Comment by Meowchestra** [comment]
Please rebase the PR against latest develop branch and I can give it a review.

**Comment by dmportella** [comment]
it only works of the textbox is focused i.e. user has pressed the textbox and it now is blinking waiting for input

it will have zero impact on anything else on the app or with people with multiple bots, apps etc They would be using something else anyway to select things

This is just standard behaviour for a number control.

**Comment by dmportella** [comment]
> 

will do

**Comment by dmportella** [comment]
@Meowchestra all rebased

<3

**Comment by troy-f** [comment]
triggered test bot

**Comment by troy-f** [comment]
@Meowchestra check passed, please do a physical function test

**Comment by Meowchestra** [comment]
Looks good to me. Only thing would be to make it also work in the performers tab boxes as it only seems to affect the solo octave and track boxes part of the main UI.

**Comment by troy-f** [comment]
@dmportella please add a todo issue/pr for the above comment

**Comment by dmportella** [comment]
> @dmportella please add a todo issue/pr for the above comment

done -> https://github.com/BardMusicPlayer/BardMusicPlayer/issues/178

**Pull request merged**
