### PR TITLE
Add Note cooldown for live-playing

### PR DESCRIPTION
**Pull request by XariusExcl**
## Note Cooldown
Hello, I implemented a feature to add a delay on notes, to prevent notes from dropping when playing "Live" (using a keyboard, gamepad or a MIDI keyboard).

image

This detects when two notes are played under the threshold set by the user, and will delay the second note to the set value. Since the game can only play one note each client-side frame, this delay should be set _higher than, but close to_ the expected frame length (ex: about 17ms for 60fps).

## Improvements

I didn't manage to make the input fields "responsive", would be nice if they were 😅

### CODE REVIEW

**Comment by GiR-Zippo** [comment]
I copyied it over to my testbench and it is working fine, but should be disabled when playing midis. 
15ms seems to be fine for the delay.
The only thing which is making me nervous is "Thread.Sleep(sleepDuration);" since it pauses the whole Ui.

**Comment by XariusExcl** [comment]
Ah, good idea! I added a [check](https://github.com/BardMusicPlayer/BardMusicPlayer/pull/89/commits/3be1420931a46081c35ebf5cc90103546154f88b) for Player.IsPlaying around the whole delay thing. IsPlaying seems to do the job.

I figured it was okay to use Thread.Sleep, since it's used in Keyboard testing (ln 248 in BmpMain.cs), and the delays are relatively short. I played around with it for a few hours and haven't had any issues.

For delays, I tried limiting my game to 30, 60 and 120 fps, and found that the closest flawless delays were 33, 17 and 9 respectively (going a bit below caused dropped notes, albeit very rarely).

**Comment by XariusExcl** [comment]
Welp, turns out I didn't check enough, as I forgot to not the IsPlaying statement, lol.

Also, I found that in `OnMidiVoice`, `if (onNote.Track != Player.Player.LoadedTrack) return;` is above the whole note playing logic, which prevents notes from being played with a MIDI keyboard when a track is loaded, ~~but also has... odd behavior.~~

- ~~When a track is not loaded, the statement returns `False`.~~
- ~~When a track is loaded but paused/stopped, the statement returns `True`.~~
- ~~When a track is playing, `OnMidiVoice` is called twice per note, and the statement returns `True`, _then_ `False`~~

~~I'm currently looking into this, as I don't think this is intended...?~~

I figured it out! The method getting called twice is to support playing all tracks with a single bard. So this is why it's `True`, then `False`, if we decided to play all tracks, the statement would be `False`, then `True`.

**Comment by XariusExcl** [comment]
I pushed a [fix](https://github.com/BardMusicPlayer/BardMusicPlayer/pull/89/commits/6ff3264bdd73848ccaee46abd4f3560ba90cf7fc) which takes care of the issue, and also changed the delay system to use async and Tasks, that way the UI should not be paused when a note is waiting to be played.

**Comment by troy-f** [comment]
Thank you for the contribution, the 1.x release isn't really taking active improvements anymore as we are mainly focused on making 2.x better.

**Pull request closed without merging**
