### PR TITLE
Rename folder to match project namespace

### PR DESCRIPTION
**Pull request by Meowchestra**
* BardMusicPlayer folder files reference BardMusicPlayer.Ui namespace all over. This renames the folder to be more proper and match the namespace.

_Similar to LightAmp._

### CODE REVIEW

**Comment by troy-f** [comment]
This is renamed in the wrong direction, we want to eliminate the ".UI" folder concept.

**Comment by Meowchestra** [comment]
Should all namespace references to UI be removed then?

**Comment by troy-f** [comment]
> Should all namespace references to UI be removed then?

yes

**Comment by troy-f** [comment]
For more context:

Originally the .UI was broken out as the main project was to be a self updating exe file that pulls everything else down as dll's from the web. We found that antivirus flagging broke this mechanism far too often, when we were testing bmp 1.3, so the idea was scrapped. There's a second reason we want the main/UI project to be without the .UI, visual studio to this day sometimes forgets what should be the default starting project, and reverts to whatever is at the top of the list.

**Comment by Meowchestra** [comment]
Makes sense. I've gone ahead and done the inverse. Namespace should all be proper in the ``BardMusicPlayer`` project now.

**Review by troy-f — APPROVED** [review]

**Pull request merged**
